In [1]:
import pandas as pd

In [2]:
x = pd.read_csv('data.csv')

In [3]:
x

name   hrs of study  marks secured
0          hi             6             60
1         bye             8             80
2       hello             6             60
3     please              3             30
4        hey              2             20
5  good night             4             40

In [4]:
import numpy

In [7]:
b = numpy.array(x)

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(6, 3)

In [10]:
b = b.reshape(-1, 1)

In [11]:
y = x["marks secured"]

In [12]:
b

array([[6],
       [8],
       [6],
       [3],
       [2],
       [4]], dtype=int64)

In [6]:
a = x["hrs of study"]

In [13]:
type(x)

pandas.core.frame.DataFrame

In [14]:
type(y)

pandas.core.series.Series

In [25]:
y.shape

(6,)

In [16]:
x.shape

(6, 3)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
mind = LinearRegression()

In [19]:
mind.fit(b , y)

LinearRegression()

In [20]:
mind.predict([[6]])

array([60.])

In [21]:
mind.coef_

array([10.])

In [22]:
import joblib

In [23]:
joblib.dump(mind , "marks secured.pk1")

['marks secured.pk1']